"""add_full_name_and_gender_in_user_table

Revision ID: 654ef9782dcd
Revises: c93e0e4341a1
Create Date: 2024-08-05 00:25:59.768756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654ef9782dcd'
down_revision = 'c93e0e4341a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
